version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
    environment:
      OLLAMA_BASE_URL: "http://backend:11434"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "11434:11434"
    restart: always