version: '3.8'

services:
  frontend:
    image: imp2/open-webui-ollama:frontend-latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8086:8080"
    depends_on:
      - backend
    environment:
      OLLAMA_BASE_URL: "http://backend:11434"

  backend:
    image: imp2/open-webui-ollama:backend-latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "11434:11434"
    restart: always