apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaa-deployment
  namespace: aaa-ns
  labels:
    app: aaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaa
  template:
    metadata:
      labels:
        app: aaa
    spec:
      containers:
        - name: standard-website
          image: imp2/standard-website:latest
          ports:
            - containerPort: 80
