apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-deployment
  namespace: ddd-ns
  labels:
    app: ddd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddd
  template:
    metadata:
      labels:
        app: ddd
    spec:
      containers:
        - name: ubuntu-firefox
          image: imp2/ubuntu-firefox:latest
          ports:
            - containerPort: 6901
