name: Actions Workflow
# https://crontab.guru/#0_22_*_*_1-5
on:
  repository_dispatch:
    types:
      - build_me
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: get payload
        run: echo ${{ github.event.client_payload.example_text }}
      - name: List Files Before
        run: |
          pwd
          ls -a
      - name: List credentials
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout_as_is
        uses: actions/checkout@v1
      - name: List Files After
        run: |
          pwd
          ls -a
      - name: Simple JS Actio
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Kevin"
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
