name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Actio
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Kevin'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"