name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: |
          pwd
          ls -a
      - name: Checkout_as_is
        uses: actions/checkout@v1
      - name: List Files After
        run: |
          pwd
          ls -a
      - name: Simple JS Actio
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Kevin'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"