name: Add Random Text File

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  add-and-commit:
    runs-on: [self-hosted, Linux, X64] # Use your own GitHub runner

    permissions:
      contents: write # Needed for pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create file with date-time name
        run: |
          FILENAME=$(date +'%Y-%m-%d-%H-%M-%S').txt
          echo $FILENAME > $FILENAME

      - name: Add random text to file
        run: |
          RANDOM_TEXT=$(openssl rand -base64 12)
          echo $RANDOM_TEXT >> $(ls *.txt | sort -n | tail -1)

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.txt"
          message: "Add $FILENAME"
          push: true
