name: Docker Ollama WebUI Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ollama-webui/**'
      - '.github/workflows/docker-ollama-webui.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ollama-webui/**'
      - '.github/workflows/docker-ollama-webui.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: imp2
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker Compose images
        run: |
          docker compose -f ./ollama-webui/docker-compose.yml build
          docker compose -f ./ollama-webui/docker-compose.yml push
