name: Docker Firefox Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build ./docker-firefox --file ./docker-firefox/Dockerfile --tag imp2/ubuntu-firefox:latest --build-arg VNC_PW_KEVIN=${{ secrets.VNC_PW_KEVIN }}

      - name: Login to Docker Hub
        run: docker login -u imp2 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push imp2/ubuntu-firefox:latest
