name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd fastapi-app
          pip install --no-cache-dir -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          cd fastapi-app
          pytest test_main.py
      - name: Build the Docker image
        run: docker build ./fastapi-app --file ./fastapi-app/Dockerfile --tag imp2/standard-api:latest
      - name: Login to Docker Hub
        run: docker login -u imp2 -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker image
        run: docker push imp2/standard-api:latest
