name: Docker Sonar App Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build ./sonar-app --file ./sonar-app/Dockerfile --tag imp2/sonar-app:latest
      - name: Login to Docker Hub
        run: docker login -u imp2 -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker image
        run: docker push imp2/sonar-app:latest
