name: Docker Firefox Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker-firefox/**'
      - '.github/workflows/docker-firefox.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docker-firefox/**'
      - '.github/workflows/docker-firefox.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: imp2
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-firefox
          build-args: |
            VNC_PW_KEVIN=${{ secrets.VNC_PW_KEVIN }}
          push: true
          tags: imp2/ubuntu-firefox:latest
