name: Docker Ollama WebUI Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Compose Images
        run: docker-compose -f ./ollama-webui/docker-compose.yml build

      - name: Login to Docker Hub
        run: docker login -u imp2 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: docker-compose -f ./ollama-webui/docker-compose.yml push
