name: Create Random Issue

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: [self-hosted, Linux, X64]
    
    permissions:
      issues: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate random string and datetime
      id: random-data
      run: |
        echo "random_string=$(openssl rand -hex 8)" >> $GITHUB_OUTPUT
        echo "current_datetime=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

    - name: Create GitHub issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        title: "Random Issue: ${{ steps.random-data.outputs.current_datetime }}"
        body: |
          ## Random Data
          
          **Random String:** ${{ steps.random-data.outputs.random_string }}
          **Date and Time:** ${{ steps.random-data.outputs.current_datetime }}
          
          This issue was automatically generated by a GitHub Actions workflow.
