name: Prettier Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  add-and-commit:
    runs-on: [self-hosted, Linux, X64] # Use your own GitHub runner
    permissions:
      contents: write # Needed for pushing changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,jsx,ts,py,tsx,json,css,scss,md,yaml,yml}
          commit_options: '--no-verify'

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Style: Format code with Prettier"
          branch: ${{ github.head_ref }}
          file_pattern: '**/*.{js,jsx,ts,py,tsx,json,css,scss,md,yaml,yml}'
          commit_options: '--no-verify'
          push_options: '--force-with-lease'

