name: Prettier Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  format:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run Prettier
        run: prettier --write "**/*.{js,jsx,ts,tsx,json,css,scss,md,yaml,yml}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Style: Format code with Prettier"
          file_pattern: "**/*.{js,jsx,ts,tsx,json,css,scss,md,yaml,yml}"