name: Prettier Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  format:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prettier Check
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: '--check **/*.{js,jsx,ts,tsx,json,css,scss,md,yaml,yml}'
          only_changed: true
        continue-on-error: true  # Prevents workflow from failing on check failure

      - name: Prettier Format
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: '--write **/*.{js,jsx,ts,tsx,json,css,scss,md,yaml,yml}'
          only_changed: true
          commit_message: "style: format code with prettier"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Style: Format code with Prettier"
          file_pattern: "**/*.{js,jsx,ts,tsx,json,css,scss,md,yaml,yml}"
