name: Add file with random number

on: [push]

jobs:
  create-random-file:
    runs-on: ubuntu-latest
    steps:
      - name: List files in repository
        run: |
          pwd
          ls -la
      - name: Check out repository branch
        run: |
          git checkout ${{ github.ref }}
          ls -la