# This workflow adds a file with a random number to the repository.
# The file is then committed to the repository.
# The workflow then creates an issue on the commit.

name: Add file with random number

on: [push]

jobs:
  create-random-file:
    runs-on: ubuntu-latest
    steps:
      - name: List files in repository
        run: |
          pwd
          ls -la
    